cursor #e3e3d8
cursor_text_color #c5c8b9

foreground            #e3e3d8
background            #12140e
selection_foreground  #2b331d
selection_background  #c1caac
url_color             #b5d087

color0   #12140e
color1   #ef816b
color2   #70d068
color3   #ffeb72
color4   #a6c572
color5   #496022
color6   #b5d087
color7   #d5dacd
color8   #83877d
color9   #ffaf9f
color10  #a9f9a2
color11  #fff2a5
color12  #cbe4a0
color13  #e7ffc0
color14  #f0ffd6
color15  #fcfff8
