cursor #e7e2d5
cursor_text_color #cbc6b5

foreground            #e7e2d5
background            #15130c
selection_foreground  #343117
selection_background  #cec7a3
url_color             #d4c871

color0   #15130c
color1   #f37b6d
color2   #77d46a
color3   #ffe872
color4   #c9bb58
color5   #62570e
color6   #d4c871
color7   #dedcd1
color8   #89887f
color9   #ffa99f
color10  #b0fea5
color11  #fff0a5
color12  #e9dd8c
color13  #fff4ab
color14  #fff8c9
color15  #fffef8
