cursor #efe0d5
cursor_text_color #d5c3b5

foreground            #efe0d5
background            #19120c
selection_foreground  #402c18
selection_background  #e1c1a4
url_color             #fcb975

color0   #19120c
color1   #ff7168
color2   #8bfc74
color3   #ffe468
color4   #efa355
color5   #743b02
color6   #fcb975
color7   #fff6ee
color8   #a39d96
color9   #ff9e98
color10  #afff9f
color11  #ffee9f
color12  #ffc58a
color13  #ffcf9f
color14  #ffe0c1
color15  #fffbf8
