# Window Rules for Hyprland
windowrule = opacity 1 0.5, match:class ^(kitty)$
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.8), match:class ^(blueman-manager)$
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.8), match:class ^(org.pulseaudio.pavucontrol)$
#windowrule = float, title:^(.*Open.*)$
#windowrule = float, title:^(.*Close.*)$
#windowrule = float, title:^(.*Rename.*)$
