cursor #e0e2e8
cursor_text_color #c2c7ce

foreground            #e0e2e8
background            #101418
selection_foreground  #23323f
selection_background  #b8c8d9
url_color             #98ccf9

color0   #101418
color1   #ff729d
color2   #7cf98c
color3   #fff772
color4   #7db9ec
color5   #204d73
color6   #98ccf9
color7   #eff7ff
color8   #959ca1
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #aad7ff
color13  #b9deff
color14  #d2eaff
color15  #f8fcff
