# BEGIN ACE
colors:
  primary:
    background: '#0C0C11'
    foreground: '#c8b4bc'
  cursor:
    text:       '#0C0C11'
    cursor:     '#c8b4bc'
  normal:
    black:      '#0C0C11'
    red:        '#4E3A45'
    green:      '#3C424E'
    yellow:     '#3D5263'
    blue:       '#4F525D'
    magenta:    '#9D1C2A'
    cyan:       '#CA3F4B'
    white:      '#c8b4bc'
  bright:
    black:      '#8c7d83'
    red:        '#4E3A45'
    green:      '#3C424E'
    yellow:     '#3D5263'
    blue:       '#4F525D'
    magenta:    '#9D1C2A'
    cyan:       '#CA3F4B'
    white:      '#c8b4bc'
# END ACE