# BEGIN ACE
colors:
  primary:
    background: '#060915'
    foreground: '#9fb9c0'
  cursor:
    text:       '#060915'
    cursor:     '#9fb9c0'
  normal:
    black:      '#060915'
    red:        '#02738D'
    green:      '#635D93'
    yellow:     '#846D9C'
    blue:       '#018B94'
    magenta:    '#0294AA'
    cyan:       '#06A7AE'
    white:      '#9fb9c0'
  bright:
    black:      '#6f8186'
    red:        '#02738D'
    green:      '#635D93'
    yellow:     '#846D9C'
    blue:       '#018B94'
    magenta:    '#0294AA'
    cyan:       '#06A7AE'
    white:      '#9fb9c0'
# END ACE