# BEGIN ACE
colors:
  primary:
    background: '#090a07'
    foreground: '#bcbbba'
  cursor:
    text:       '#090a07'
    cursor:     '#bcbbba'
  normal:
    black:      '#090a07'
    red:        '#797873'
    green:      '#84513B'
    yellow:     '#817F7A'
    blue:       '#7F8079'
    magenta:    '#83827E'
    cyan:       '#A08574'
    white:      '#bcbbba'
  bright:
    black:      '#838282'
    red:        '#797873'
    green:      '#84513B'
    yellow:     '#817F7A'
    blue:       '#7F8079'
    magenta:    '#83827E'
    cyan:       '#A08574'
    white:      '#bcbbba'
# END ACE