# BEGIN ACE
colors:
  primary:
    background: '#0C0A06'
    foreground: '#9eabdd'
  cursor:
    text:       '#0C0A06'
    cursor:     '#9eabdd'
  normal:
    black:      '#0C0A06'
    red:        '#906D4C'
    green:      '#74865C'
    yellow:     '#A69D49'
    blue:       '#214FB3'
    magenta:    '#4F63AB'
    cyan:       '#2E5DCC'
    white:      '#9eabdd'
  bright:
    black:      '#6e779a'
    red:        '#906D4C'
    green:      '#74865C'
    yellow:     '#A69D49'
    blue:       '#214FB3'
    magenta:    '#4F63AB'
    cyan:       '#2E5DCC'
    white:      '#9eabdd'
# END ACE