# BEGIN ACE
colors:
  primary:
    background: '#120100'
    foreground: '#e6bdaf'
  cursor:
    text:       '#120100'
    cursor:     '#e6bdaf'
  normal:
    black:      '#120100'
    red:        '#9C4230'
    green:      '#AB4A37'
    yellow:     '#B95B45'
    blue:       '#C96C54'
    magenta:    '#D0765D'
    cyan:       '#BF856D'
    white:      '#e6bdaf'
  bright:
    black:      '#a1847a'
    red:        '#9C4230'
    green:      '#AB4A37'
    yellow:     '#B95B45'
    blue:       '#C96C54'
    magenta:    '#D0765D'
    cyan:       '#BF856D'
    white:      '#e6bdaf'
# END ACE