# BEGIN ACE
colors:
  primary:
    background: '#080A0B'
    foreground: '#c5c8c9'
  cursor:
    text:       '#080A0B'
    cursor:     '#c5c8c9'
  normal:
    black:      '#080A0B'
    red:        '#30404F'
    green:      '#544F4C'
    yellow:     '#666561'
    blue:       '#8D8471'
    magenta:    '#5A7789'
    cyan:       '#6F8F9F'
    white:      '#c5c8c9'
  bright:
    black:      '#898c8c'
    red:        '#30404F'
    green:      '#544F4C'
    yellow:     '#666561'
    blue:       '#8D8471'
    magenta:    '#5A7789'
    cyan:       '#6F8F9F'
    white:      '#c5c8c9'
# END ACE