# BEGIN ACE
colors:
  primary:
    background: '#060B18'
    foreground: '#c2c1ce'
  cursor:
    text:       '#060B18'
    cursor:     '#c2c1ce'
  normal:
    black:      '#060B18'
    red:        '#4E5671'
    green:      '#3B5D81'
    yellow:     '#5D708D'
    blue:       '#917488'
    magenta:    '#718BA5'
    cyan:       '#7E9EC1'
    white:      '#c2c1ce'
  bright:
    black:      '#878790'
    red:        '#4E5671'
    green:      '#3B5D81'
    yellow:     '#5D708D'
    blue:       '#917488'
    magenta:    '#718BA5'
    cyan:       '#7E9EC1'
    white:      '#c2c1ce'
# END ACE