[colors.primary]
background = '#1a1110'
foreground = '#f1dedc'

[colors.selection]
text = '#f1dedc'
background = '#73342b'

[colors.cursor]
text = '#1a1110'
cursor = '#ffb4a9'

[colors.normal]
black   = '#1a1110'
red     = '#ff7472'
green   = '#99ff7f'
yellow  = '#ffe472'
blue    = '#f29c90'
magenta = '#76362d'
cyan    = '#ffb4a9'
white   = '#fff1ef'

[colors.bright]
black   = '#a59a99'
red     = '#ffa09f'
green   = '#b8ffa5'
yellow  = '#ffeea5'
blue    = '#ffbfb5'
magenta = '#ffcac2'
cyan    = '#ffddd8'
white   = '#fff9f8'
