[colors.primary]
background = '#121318'
foreground = '#e3e1e9'

[colors.selection]
text = '#e3e1e9'
background = '#374379'

[colors.cursor]
text = '#121318'
cursor = '#b8c4ff'

[colors.normal]
black   = '#121318'
red     = '#ff7297'
green   = '#7fff94'
yellow  = '#fff972'
blue    = '#a1aef2'
magenta = '#394376'
cyan    = '#b8c4ff'
white   = '#eff2ff'

[colors.bright]
black   = '#999ba5'
red     = '#ff9fb8'
green   = '#a5ffb4'
yellow  = '#fffba5'
blue    = '#c2ccff'
magenta = '#cdd5ff'
cyan    = '#dfe4ff'
white   = '#f8f9ff'
