[colors.primary]
background = '#1a1110'
foreground = '#f1dfdb'

[colors.selection]
text = '#f1dfdb'
background = '#733428'

[colors.cursor]
text = '#1a1110'
cursor = '#ffb4a5'

[colors.normal]
black   = '#1a1110'
red     = '#ff7572'
green   = '#99ff7f'
yellow  = '#ffe472'
blue    = '#f29c8b'
magenta = '#763629'
cyan    = '#ffb4a5'
white   = '#fff2ef'

[colors.bright]
black   = '#a59b99'
red     = '#ffa19f'
green   = '#b7ffa5'
yellow  = '#ffeea5'
blue    = '#ffbfb2'
magenta = '#ffcac0'
cyan    = '#ffddd6'
white   = '#fff9f8'
